export const authConstant ={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}
export const userConstant ={
    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE"
}
export const categoryConstant={
    GETALLCATEGORY_REQUEST:"GETALLCATEGORY_REQUEST",
    GETALLCATEGORY_SUCCESS:"GETALLCATEGORY_SUCCESS",
    GETALLCATEGORY_FAILURE:"GETALLCATEGORY_FAILURE",
    
    ADDNEW_CATEGORY_REQUEST:"ADDNEW_CATEGORY_REQUEST",
    ADDNEW_CATEGORY_SUCCESS:"ADDNEW_CATEGORY_SUCCESS",
    ADDNEW_CATEGORY_FAILURE:"ADDNEW_CATEGORY_FAILURE",

}
export const productsConstant ={
    GET_ALL_PRODUCTS_REQUEST:"GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE",

    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
}
export const getAllDataConstant ={
    GET_ALL_DATA_REQUEST:"GET_ALL_DATA_REQUEST",
    GET_ALL_DATA_SUCCESS:"GET_ALL_DATA_SUCCESS",
    GET_ALL_DATA_FAILURE:"GET_ALL_DATA_FAILURE"
}